# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveR
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ReactiveRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveRUITests' do
    # Pods for testing
  end

end
